# Generated by Django 3.2.9 on 2022-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('two_auth', models.CharField(max_length=32)),
                ('token', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
