# Generated by Django 3.2.9 on 2022-07-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FistProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('stage', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('likers', models.CharField(blank=True, max_length=255)),
                ('meeting_start_time', models.DateTimeField(null=True)),
                ('meeting_end_time', models.DateTimeField(null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('two_auth', models.CharField(blank=True, max_length=32)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('is_admin', models.BooleanField(default=False)),
                ('commented', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fistprocedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('fist', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('xs', models.CharField(max_length=1024)),
                ('ys', models.CharField(default='2022年第1季度,2022年第2季度,2022年第3季度,2022年第4季度', max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='fistprocedure',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AddField(
            model_name='fistprocedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profitable', models.FloatField(default=0.0)),
                ('future_proof', models.FloatField(default=0.0)),
                ('market', models.FloatField(default=0.0)),
                ('branding', models.FloatField(default=0.0)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fistprocedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
    ]
