# Generated by Django 3.2.9 on 2022-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220625_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='fistprocedure',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fistprocedure',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
