# Generated by Django 3.2.9 on 2022-06-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220625_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='fistprocedure',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.fistprocedure'),
        ),
    ]
