# Generated by Django 3.2.9 on 2022-06-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220625_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fistprocedure',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
    ]
