# Generated by Django 3.2.9 on 2022-06-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_fistprocedure_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedfile',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.fistprocedure'),
        ),
    ]
