# Generated by Django 3.2.9 on 2022-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_useruploadedfile_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fistprocedure',
            name='metting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
