# Generated by Django 3.2.9 on 2022-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fistprocedure_metting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
