# Generated by Django 3.2.9 on 2022-06-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='vote',
            new_name='agree',
        ),
    ]
