# Generated by Django 3.2.9 on 2022-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_vote_comment_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='fistprocedure',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
