# Generated by Django 3.2.9 on 2022-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_fistprocedure_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fistprocedure',
            old_name='metting_time',
            new_name='meeting_end_time',
        ),
        migrations.AddField(
            model_name='fistprocedure',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fistprocedure',
            name='metting_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
