# Generated by Django 3.2.9 on 2022-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fistprocedure_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedfile',
            name='name',
            field=models.CharField(default='TempFileName', max_length=255),
            preserve_default=False,
        ),
    ]
