# Generated by Django 3.2.9 on 2022-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220701_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fist_grade',
            field=models.IntegerField(default=0),
        ),
    ]
