# Generated by Django 3.2.9 on 2022-07-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='agree',
        ),
    ]
