# Generated by Django 3.2.9 on 2022-07-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_comment_agree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fist_grade',
            new_name='grade',
        ),
    ]
