# Generated by Django 3.2.9 on 2022-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220704_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fistprocedure',
            name='commented',
        ),
        migrations.AddField(
            model_name='user',
            name='commented',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
